export const itemsArr = [
  {
    type: "Points per click",
    name: "PPC 1",
    amount: 0,
    price: 100,
    buffPerClick: 1,
  },
  {
    type: "Points per click",
    name: "PPC 2",
    amount: 0,
    price: 500,
    buffPerClick: 10,
  },
  {
    type: "Points per click",
    name: "PPC 3",
    amount: 0,
    price: 2500,
    buffPerClick: 100,
  },
  {
    type: "Points per click",
    name: "PPC 4",
    amount: 0,
    price: 5000,
    buffPerClick: 200,
  },
  {
    type: "Points per second",
    name: "PPS 1",
    amount: 0,
    price: 100,
    buffPerClick: 0,
    buffPerSecond: 1,
  },
  {
    type: "Points per second",
    name: "PPS 2",
    amount: 0,
    price: 500,
    buffPerClick: 0,
    buffPerSecond: 10,
  },
  {
    type: "Points per second",
    name: "PPS 3",
    amount: 0,
    price: 2500,
    buffPerSecond: 100,
  },
  {
    type: "Points per second",
    name: "PPS 4",
    amount: 0,
    price: 5000,
    buffPerSecond: 200,
  },
];
